	std::string ip;
	ip += lexical_cast<string>(descPayload[2]);
	ip += ".";
	ip += lexical_cast<string>(descPayload[3]);
	ip += ".";
	ip += lexical_cast<string>(descPayload[4]);
	ip += ".";
	ip += lexical_cast<string>(descPayload[5]);
	desc.ipMulticast = ip;
	desc.port = (descPayload[6] << 8) + descPayload[7];
